name: Sync to GitHub

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  delete:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    # Adjust this label to match your Forgejo runner (e.g. self-hosted/ubuntu-latest/docker)
    runs-on: docker
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Push mirror to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${GH_TOKEN:-}" ]; then
            echo "GH_TOKEN secret must be set in Forgejo repo settings > Actions > Secrets." >&2
            exit 1
          fi

          git config --global user.email "actions@forgejo"
          git config --global user.name "Forgejo Actions"

          # Ensure we have all refs locally
          git fetch --all --tags --prune

          # Add GitHub remote with token (fixed target repo)
          git remote remove github 2>/dev/null || true
          git remote add github "https://${GH_TOKEN}@github.com/Sunwood-ai-labs/forgejo-to-github.git"

          # Mirror all refs (branches, tags, deletions) to GitHub
          git push --mirror github
